name: Deploy to Firebase Hosting on PR

on:
  pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./dev-connect
        run: yarn install

      - name: Build project
        working-directory: ./dev-connect
        run: yarn run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIR_SOCIAL_MEDIA_PLATFORM }}
          projectId: fir-social-media-platform
          entryPoint: ./dev-connect  
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
