name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./dev-connect
        run: yarn install

      - name: Build project
        working-directory: ./dev-connect
        run: yarn run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIR_SOCIAL_MEDIA_PLATFORM }}
          channelId: live
          projectId: fir-social-media-platform
          entryPoint: ./dev-connect  # Set entryPoint to the directory containing firebase.json
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
